---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: references.bib
---

# General introduction {-} 
\adjustmtc
\markboth{Introduction}{}

\noindent When I started working on this thesis at the beginning of 2018, carry trade was a well-established investment strategy. Now, in 2021, we are in a brand new world, where a sort of zero lower bound (ZLB) on interest rate differentials and the popularization of crypto-assets^[@stix2021 [\text{p.} 65] uses "the term crypto-asset instead of crypto-currency or virtual-currency because crypto-assets lack the characteristics of conventional currencies (i.e. with respect to their usability for daily transactions or to provide a stable unit of account)."] is making carry trade less implemented. In my opinion, this is a reaction to the dovish monetary policy implemented around the globe as a response to the COVID-19 crisis^[This crisis is also known as the coronavirus (COVID-19) pandemic. See @cantu2021 for a database gathering the policy responses to the COVID-19 crisis.]. A report by the @committeeontheglobalfinancialsystemcgfs2021 [\text{p.} 12] indicates that carry trade "became less attractive in the intermediate aftermath of the Covid-19 shock." In a nutshell, the carry trade activity is very likely to occur with the presence of interest rate differentials between two currencies. Nevertheless, this new puzzle does not make the main research question of this thesis fade away: how does carry trade impact the real economy activity? With the outburst of the 2007-08 global financial crisis (GFC), the carry trade, an "obscure corner of international finance" [@jorda2012 \text{p.} 74], has shown its dangers for the real economy. For example, as reported by the press at the beginning of this crisis [@fackler2007], Japanese individuals faced billionaire losses with leveraged carry trade, making life savings disappear suddenly.

In the classic definition, carry trade is a transaction of borrowing a low interest rate currency (e.g., Swiss franc) to invest in a high interest currency (e.g., Brazilian real). In this thesis, the carry trade instrument is the offshore futures market, where the transaction in the investment date demands taking "a short position in a funding currency and a long position in the destination currency." [@bankforinternationalsettlements2015, \text{p.} 9] Following closely @brunnermeier2008, carry trade is proxied by the positions data in futures market published by the United States (U.S.) Commodity Futures Trade Commission (CFTC). As leveraged investments, their sudden stop contributes to the financial amplification of negative externalities of international capital flows.^["When a large number of borrowers in an economy experience financial difficulty at the same time and engage in deleveraging, their collective actions lead to asset price declines and exchange rate depreciations, which frequently reduce the value of the assets on borrowers' balance sheets and/or increase the value of their liabilities. As a result, the creditworthiness of borrowers declines further, leading to a feedback loop of further deleveraging, asset price and exchange rate depreciations, and balance sheet effects." [@erten2019, \text{p.} 10]]

In a broader theoretical perspective, real variables are not independent of monetary variables, invalidating the classical dichotomy. Despite its redundancy, money is central in a monetary economy. Moreover, as explained by the monetary circuit, the policy interest rate set by the central bank is the first step to investigate real economic activity [@rochon2015 \text{p.} 332]. The initial injection or destruction of money in the system is crucial to understanding the linkages between the carry trade activity and the real economy. With each central bank following its policy objectives, monetary swings almost immediately impact other countries in the current international monetary system.

This has not always been the case. Under the Bretton Woods system (1944-71), "globally fixed exchange rates against the U.S. dollar tied to the price of gold and capital controls" [@fields2015 \text{p.} 146] created a sort of sandbox for the countries' monetary policy. With capital controls being the norm [@grabel2016], the negative foreign externality of these policies would take a considerable time to reach other countries, notably developing countries. The end of the Bretton Woods is one of the main cornerstones of the actual globalized financial market. Along with the U.S. dollar imposed as the "global currency," another fundamental characteristic of the current international monetary system is the imposition of deregulation.

Basically, financial deregulation is the lifting of barriers and controls in the financial sector. The main idea behind it has been the promotion of efficient and competitive financial markets [@correa2015]. Hence, by freely flowing worldwide, capital would reach the places where it is most needed. This would be possible due to the capital account openness, with less (or the absence of) capital controls. The new macroeconomic policy framework post-Bretton Woods imposed a "trilemma" for all national policymakers, except the United States. As summarized by @obstfeld2004 [\text{p.} 30], these policymakers are constrained to two of these three policy goals: "(i) full freedom of cross-border capital movements; (ii) a fixed exchange rate; and (iii) an independent monetary policy oriented toward domestic objectives." With very few exceptions, most countries have chosen goals (i) and (ii) imposing a floating exchange rate regime. With the exponential growth of financial innovations, a "global financial cycle" was created, rather imposing a "dilemma" for policymakers [@rey2015]. This restricts even further the policy goals for nations, where "independent monetary policies are possible if and only if the capital account is managed, directly or indirectly, regardless the exchange-rate regime" [@rey2015, \text{p.} 21]. Here lies the importance of capital controls in a globally coordinated manner.

With finance displacing production from the core of our economic system, a new type of capitalism has been formed. @minsky1996 called this new stage of development money manager capitalism. It is a finance-led regime with two main propositions, following @aglietta2005 [\text{p.} xii]: "better risk-sharing and greater economic efficiency in the allocation of capital" and "Shareholder primacy puts an end to the usurpation of power that characterized ‘managerial capitalism’. It (re-)establishes the respect of private property – the linchpin of capitalism." @boyer2011 also highlights this new capitalist regime, _la financiarisation_. Concisely, @hein2015 [\text{p.} 182] says that the "combination of the liberalization of national and international financial markets, the introduction of the new financial instruments, changes in corporate governance, and so on, may lead to a dysfunctional increase in finance, which increases instability and hinders investment and economic growth, as has been analyzed in the literature on 'financialization' and 'finance-dominated capitalist'."^[Section \@ref(twotwo) provides a deeper explanation of financialization.]

Overall, both developed and developing countries followed this path towards more flexibility on international capital movements. Nevertheless, the pace and timing of implementing an open capital account and a floating exchange rate regime were drastically different. On the one hand, developed countries started this process much earlier with a very smooth implementation. On the other hand, developing countries have adhered to financial deregulation without being well developed to be able to. "This recommendation became a key part of the Washington Consensus^["The term *Washington Consensus* was coined by @williamson1990 as a way to codify the economic liberalization policies encouraged by international financial institutions (IFIs) as part of their strategy of structural reforms."[@ocampo2004, \text{p.} 293]]; and since the 1980s mainstream economists, the World Bank and the IMF have been advising developing countries to reform their financial systems, i.e. to reduce government intervention in order to get 'interest rates right' [@worldbank1989; @long1991, \text{p.} 169]." [@karwowski2017, \text{p.} 63] The result of this rapid deregulation was the spread of the international financial crisis in several developing countries. Notably, a selective list of the most relevant crashes in the developing world is: Latin America debt crisis (the 1980s), Argentina (early 1980s), Asian crises (1997-98), Russia (1998), Brazil (1999), and Argentina (2001-02). These crises' higher frequency, intensity, and contagion did not hold back financialization. Quite the opposite, financial globalization has been intensified. Consequently, it did not take long to see a developed country in the epicenter of such crises. The GFC that started in the U.S. showed how dysfunctional finance has become, spreading recession worldwide. Indeed, the Emperor has no clothes.

Financial innovations, e.g., credit default swaps and derivatives, were among the main drivers of the GFC. These new financial instruments have been negotiated in the non-bank financial intermediation (NBFI) sector. This sector is "a broad measure of all non-bank financial entities, and comprising all financial institutions that are not central banks, banks or public financial institutions" [@financialstabilityboard2020, \text{p.} 3]. At end-2019, almost half of the financial sector assets was attributable to the NBFI sector, estimated in 200.2 trillion of U.S. dollars [@financialstabilityboard2020]. Carry traders profit from this relatively unregulated sphere of the financial sector. Notably, hedge funds, who are "large carry players" [@gabor2015, \text{p.} 75], accounted for 2.8% of the NBFI assets in this period [@financialstabilityboard2020]. Nevertheless, traces of the carry trade activity are also present in other sectors. By occurring mostly off-balance sheet, tracking and measuring carry trade is a puzzle for all, especially central banks and researchers.

The Bank for International Settlements (BIS) Triennial Central Bank Survey provides a comprehensive compilation on global foreign exchange and over-the-counter (OTC), i.e., off-balance sheet, derivatives market. In April 2019, the daily turnover of OTC foreign exchange instruments averaged 6.6 trillion U.S. dollars  [@bankforinternationalsettlements2019]. According to Figure \@ref(fig:Figure31) in Chapter \@ref(three), this daily turnover exceeds by 40 times the daily amount of world trade in U.S. Dollars in 2019 (in comparison to a ratio of 21 in 1989). Albeit not illustrating the size of the carry trade activity, it shows how much finance is disconnected from the real economy needs. To date, the closest picture of carry trade we may have comes from the positioning data supplied by the U.S. Commodity Futures Trade Commission (CFTC). To better understand the impacts of carry trade in the real economy, we need to use this volume indicator, not the usual calculation of carry trade excess returns or carry-to-risk ratios (expected profitability) that is widely used in the literature.

Recent crises did not discourage the increase in the disconnection between the monetary and real sides of the economy. Nonetheless, central banks work hard to tame the adverse effects of monetary variables on the real economy. Paradoxically, these are the same institutions that are central to this disconnection. In general, the main policy response during these crises was monetary easing or tightening, depending on the circumstances. As a side-effect of the degree of liquidity in global markets, exchange rate volatility has been heavily influenced by speculation with leveraged financial instruments in futures markets. As a result, trade is directly impacted by this change in currency values. This shows how carry trade activity could impact the real economy. Likewise, by being very risky by nature, carry trade reinforces the systemic risk in the global economy.

Price volatility is one of the main drivers of speculation in financial markets. @kaldor1976 [\text{p.} 111] defines speculation "as the purchase (or sale) of goods with a view to re-sale (re-purchase) at a later date, where the motive behind such action is the expectation of a change in the relevant prices relatively to the ruling price and not a gain accruing through their use, or any kind of transformation effected in them or their transfer between different markets." Thus, rather than entering the forward market to reduce the risk from uncertain future prices, as hedgers do, speculators "assume the risks" [@kaldor1976, \text{p.} 116]. As documented by @brunnermeier2008, carry trade is strongly linked to currency crash risk. The sudden unwinding of carry trade positions can systemically spread negative shocks that go far away from the foreign exchange market [@hattori2009]. Being leveraged bets, carry trade is very sensitive to market liquidity and funding, which often cause the unwinding of positions [@brunnermeier2008]. Other global or local events can also trigger this unwind, e.g., the GFC, COVID-19, or future climate crises. Given the size of the transactions related to the carry trade activity, our interconnected financial system amplifies their shock worldwide, increasing the systemic risk.

Global speculators profit from the capital account liberalization widely implemented worldwide. In theory, "[c]apital account openness can create more financial sector competition, enable portfolio diversification, and provide finance for current account imbalances." [@gallagher2014, \text{p.} 3] For developed countries, like Switzerland, capital account openness may be significantly beneficial because they have "reached a certain threshold of institutional capabilities needed to manage its financial sector." [@gallagher2014, \text{p.} 3] Nevertheless, for developing countries like Brazil, free movement of international capital seems to be more associated with financial crises and inequality [@gallagher2014]. Further, after the GFC, @gallagher2014a [\text{p.} 2] explain that Brazil attracted carry traders, who profited from "the high domestic policy rate and the sophistication of the Brazilian financial system". As a result, there was an "upward pressure on the exchange rate, which has come with higher commodities prices, leading to what we refer to here as 'a financialization of the resource curse'." [@gallagher2014a, \text{p.} 2] Along the same lines, the excessive net flows may impact negatively developing countries in a sort of financial Dutch disease^["The Dutch disease is a country’s chronic exchange rate overvaluation caused by the exploitation of abundant and cheap resources, whose production and export is compatible with a clearly more appreciated exchange rate than the exchange rate that makes internationally competitive the other business enterprises in the tradable sector that use the most modern technology existing worldwide." [@bresser-pereira2013, \text{p.} 372]] [@botta2021]. 

In this thesis, carry trade and currency carry trade are used interchangeably. In the financial world, there are many different forms of carry trade.^[See more details in Subsection \@ref(twothreeone).] In fact, they have always been central to our modern financial systems. For example, banks and insurance companies do it. By paying low interest rates on demand deposits, banks gain higher interest rates by making long-term loans. Regarding insurance companies, premiums are paid for the assumed risks [@lee2020]. There is also the equity carry trade, which arises from equity return differentials between countries [@girardin2019]. Additionally, the carry trade is often named after the funding currency, e.g., dollar carry trade or yen carry trade. Some common characteristics among all carry trades are: "leverage, liquidity provision, short exposure to volatility, and a 'sawtooth' return pattern of small, steady profits punctuated by occasional large losses" [@lee2020, \text{p.} 3]. In general, carry trade is a market "anomaly," where leverage is used "to harvest arbitrage profits, a way to buy low and sell high" [@mehrling2010, \text{p.} 83].

Some currencies have been more involved than others in the currency carry trade activity. Notably, yields and financial integration, linked to currency internationalization, are among the main explanatory factors of the carry trade. This thesis focuses on two currencies: Swiss franc (funding currency) and Brazilian real (target currency). Both present strong push factors to be implied in the carry trade activity. Respectively, the former has maintained a very low interest rate, while the former has been implementing a relatively very high policy rate for a long time.^[See Figure \@ref(fig:Figure311) for the interest rate differentials between Switzerland and Brazil and the United States. For the U.S. policy rate, check Figure \@ref(fig:Figure30).] Both currencies are internationalized, although to a lesser extent in the case of the Brazilian real. According to the BIS data on turnover of OTC foreign instruments by currency, the Swiss franc ranks 7^th^ in the world, while Brazil ranks 19^th^ (see Table \@ref(tab:TableAA21) in Appendix \@ref(appendixa2)). Furthermore, the choice is also motivated by the lack of studies on both, especially on Brazil. In addition, the Swiss franc and Brazilian real fit relatively well three out of five attributes for appealing currencies in international markets put forward by [@cohen2015, \text{p.} 3]: "financial development, foreign policy ties, [...] and effective governance (safe management of the currency)." Economic size and military reach are the two attributes that are questionable for both currencies.

Indeed, yields and currency internationalization are key factors characterize the Swiss franc as a funding currency and the Brazilian real as a target currency. Meanwhile, both currencies present specific characteristics in the context of the carry trade activity. On the one hand, the Swiss National Bank (SNB) was one of the first to implement a flexible exchange rate regime in 1974 [@rossi2015]. Along with the role of supplying global liquidity with its low (or negative) policy interest rate, the Swiss franc is also a crucial safe asset during economic turmoils [see @galati2007; @ranaldo2010; @guillaumin2012]. As pointed out by @baltensperger2017 [\text{p.} 178], there is a "Swiss interest rate bonus"^[This has not always been the case [see @laurent2014]. The bonus is related to Switzerland's economic development, with "exceptional political, economic, and monetary stability" [@baltensperger2017, \text{p.} 178].], which leads "investors to pay a premium for holding Swiss franc fixed income assets". Therefore, this dual role for the Swiss franc makes it a fascinating case to study, notably in times of negative policy interest rates. Like Brazil, Switzerland also struggles with the impact of the exchange rate on its trade balance. Nonetheless, it is an entirely different problem related to its appreciation, whether in crisis or not. In September 2011, the SNB shocked financial markets by implementing a peg to the euro [@vallet2014], which lasted until January 2015. Another innovation implemented by the SNB is the negative policy rate. More importantly, the risk factor mainly drives Swiss franc dynamics, notably in turbulent times [@fink2022], which highlights its role as a safe haven currency. The dual role (funding and safe haven currency) of the Swiss franc makes it a very interesting case to study in the context of the carry trade activity. In other words, it acts as a funding currency during good times and as a safe haven currency in turbulent periods. Therefore, "it is not the interest rate spread, as emphasised in the carry trade literature, the most consistent and robust predictor of safe haven status" [@habib2012, \text{p.} 57].

On the other hand, Brazilian real was a major target currency after the 2007-08 global financial crisis. Several factors played a role in this attractiveness: very high policy interest rate (relative to other major currencies), prosperous macroeconomic indicators, and an emerging role in global governance. After a period of hyper inflation and high volatility in interest rates in the 1990s, Brazil opted for inflation targeting in 1999 [@barbosa-filho2009] after the successful launch of the Brazilian real in 1994. This choice aimed to improve the macroeconomic stability of the country, in a context of increasing international openness linked to its status as an emerging country [@artus2004; @libanio2010]. In 2010, former Brazilian Treasury Minister Guido Mantega announced: "We’re in the midst of an international currency war, a general weakening of currency. This threatens us because it takes away our competitiveness" [@financialtimes2010]. This "currency war" was an indirect effect of the expansionist monetary policies of the developed countries, which sought to provide liquidity to revive their economies. However, this liquidity also ended up impacting the rest of the world, as well as their own countries [@grabel2018]. Therefore, exchange rates of developed and developing countries were affected, modifying trade patterns artificially. Consequently, economic output was also being impacted, which was the primary concern of the Brazilian government while questioning its currency's very unusual appreciation.

Two points are essential to understand the exchange rate problem that arises from the carry trade activity. First, in the case of the Federal Reserve's response to the GFC, "the excess liquidity added to U.S. financial markets was then exported through carry trades, using dollar borrowings to invest in higher-yielding assets in emerging economies. There, the inflow of dollars used to buy these countries' assets tended to be mopped up by their central banks in sterilization operations intended to prevent inflation and appreciation of their currencies" [@darista2018, \text{p.} 11]. Second, these sterilization operations themselves are also considered carry trade activity [@gabor2015]. Therefore, by pilling up the excess flows as international reserves, central banks of emerging economies worsened the problem by pressuring the exchange rate further. It was "setting in motion a sorcerer's apprentice scenario" [@darista2018, \text{p.} 11], where emerging economies' central banks fostered more speculative currency activity by trying to defend themselves. Hence, a vicious economic cycle with carry trade as a major driver.

Non-cooperative equilibria result from selfish central banks that focus only on the domestic effects of their monetary policies. The lack of collective good in central banking and deregulated global financial markets foster the carry trade activity. The U.S. monetary policy impacts the world economy, not only the U.S., in the "global financial cycle" [@miranda-agrippino2020]. International monetary policy spillovers are also well-documented for other central banks [e.g., @fratzscher2016 for the European Central Bank; @schmidt2018 for the Bank of England]. The "currency hierarchy" [@cohen1998; @depaula2017] is central to explaining the imbalances generated in the existing international monetary system. According to the @bankforinternationalsettlements2019, the U.S. dollar accounted for almost half of the daily turnover of OTC foreign exchange instruments in 2019, while the euro, the Japanese yen, and the British sterling accounted for roughly 60%. Other countries have to find solutions to this non-cooperative system. Notably, carry trade profits from emerging countries' target currencies with "high interest rates and profitable exchange rate movements", which expose the "international monetary subordination necessary to compensate for these currencies’ lower standing in the international currency hierarchy" [@bonizzi2020, \text{p.} 183].

Our current international monetary system is susceptible to shocks, as exposed by the numerous financial crises in the last 40 years. Once again, the world economy is suffering from a global crisis, the COVID-19 crisis. One more time, generalized volatility in the global financial markets and global recession negatively impact people's lives. The exorbitant power of the U.S. dollar is still problematic to the global economy. Having a major currency in the international monetary system was one of the major critiques Keynes made in the debates on the Bretton Woods system, when he rather advocated for a system based on "currency multilateralism" [@keynes1978b, \text{p.} 25]. With a climate crisis very next to our days, finance needs to be revamped to work for people's good, for example, as proposed by the Wall Street Consensus [@gabor2021].

In a dysfunctional system, anomalies will not cease to develop and perpetuate. It is even worse in a system fostered by selfishness. Following the global recession created by the GFC, the dysfunctional finance present in our current system may lead to even worse crises after several crises of lesser magnitude. This thesis aims to investigate one of the prominent anomalies of this system, the carry trade. The carry trade activity links both monetary and real sides of the economy by speculating with currencies. Hence, it is not only the monetary and financial structures that matter for this financial activity, but also the real economy. The main contribution of this thesis is to provide reproducible empirical evidence to understand better the dynamics of the carry trade activity in Brazil and Switzerland. Moreover, by investigating the political economy of the carry trade, this thesis also aims to contribute to further reflections about our dysfunctional system, not only this anomaly.

The remainder of this thesis is structured as follows. In Chapter \@ref(two), the research design of the thesis is presented. This chapter intends to explore further conceptual and theoretical elements, which could not be developed in the subsequent chapters due to the required length of publishers. In the following, three chapters take the form of academic articles. All three are empirical developments of the research question using the CFTC data as a proxy for carry trade. As highlighted by @galati2007 [\text{p.} 38], "[d]ata on the net open positions of non-commercial traders in different currency futures traded on the Chicago Mercantile Exchange have been the most widely used measure of carry trade activity in the futures market." Chapter \@ref(three) investigates the carry trade in developed and developing countries, as published in @tomio2020. Next, Chapter \@ref(four) analyses the Swiss franc carry trade activity in the context of negative policy interest rates. Lastly, Chapter \@ref(five) explores the political economy of carry trade, by confronting the real economy effects of carry trade activity in the current structural power of the international monetary system. The choice to focus on the Swiss franc and Brazilian real also relies on expanding the carry trade literature to other currencies. The Japanese yen is one of the main currencies investigated in this literature. Moreover, Chapter \@ref(three) and Chapter \@ref(four) are written based on @nishigaki2007 and @fong2013, who investigate the yen carry trade with specific measures of the carry trade proxy. Similarly, Chapter \@ref(five) uses the most known measure of the CFTC carry trade proxy in the literature, popularized by @brunnermeier2008. Finally, the chapter [General conclusion] summarizes the main contributions and discusses future research.