---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: references.bib
---

# General conclusion {-}

When finishing this thesis, the carry trade is better revealed. In the carry trade literature, it seems that it is a hidden investment strategy. Indeed, one of the main reasons for the difficulty in uncovering the carry trade is the lack of public data. Since most of its transactions occur in the OTC market, researchers cannot analyze the real numbers of this speculative activity. Nevertheless, it is possible to get closer to these numbers with the CFTC data. Contrary to the vast literature that focuses on the profit-maximizing analysis of the carry trade, this thesis concentrates on the carry trade effects on the real economy. More specifically, the real economy impacts of this specific type of currency speculation on Switzerland and Brazil. Although economically very different, both countries suffer similarly with the carry trade. The struggle is related to the pervasive financial effects on their real economies.

Technically, this thesis pursued an investigation rooted in realism, skepticism, empiricism and simplified models. By using assumptions as close as possible to the real economy (realism/realisticness), the reliability of current knowledge (skepticism) on the carry trade literature is empirically tested (empiricism) in simplified models (the principle of parsimony). Although mathematical formalization is minimized, scientific rigor is maintained in the quantitative sections of this thesis. Along with the empirical analysis, a political economy approach is employed to analyze the carry trade realistically. Methodologically, both reductionist and holistic approaches are implemented. From this perspective, this thesis aims to contribute to the better understanding of the immense carry trade puzzle. Each one of the four chapters in this thesis is constructed keeping in mind the main research question: **How does carry trade impact the real economy activity?**

In Chapter \@ref(two) (*Research design*), theoretical and conceptual frameworks are exposed to pursue the investigation of the carry trade effects in Switzerland and Brazil. Using the concept of financialization, carry trade may be characterized as an anomaly of our current finance-dominated system. In essence, it is a dysfunctional system for several reasons. Regarding the carry trade, it is a global crisis-prone activity. As characterized in-depth in this chapter, the carry trade reveals itself as a pervasive investment strategy par excellence. Therefore, there is a need to understand its effects on the real economy better. Furthermore, the political economy approach is crucial to discuss possible ways to tame the negative effects of the carry trade. Instead of creating a system focused on long-term development, global governance opted for deregulated financial capitalism and its short-termism. 

Although the carry trade is not a relatively new investment strategy, the recent developments of financialization amplified its trading volume. Academically, it is a quite recent topic, mainly explored after the debate on the invalidity of the UIP hypothesis in the 1980s. "This phenomenon has given birth to a famous and widespread strategy, namely the carry trade, which appeals to a growing population of speculators." [@ames2017, \text{p.} 185] In addition, the dissemination of this speculative strategy is linked to the common ground found by practitioners and academics. There is a vast literature on the profit maximization of the carry trade. On the other hand, researchers have also focused on the risks of this activity to the world economy, as demonstrated by the currency crashes [e.g. @brunnermeier2008]. With the popularization of financial investments lead by fintechs, FX trading is gaining a large number of adopters. With the idea of the invalidity of the law of one price being spread to young gamers, as evidenced in the game Fortnite by @stadtmann2020, it will not take long to a generalization of currency speculation. In a gamified manner, carry trade can become a even wilder roller-coaster ride. Consequently, this would amplify much further its pervasive effects.

Chapter \@ref(three) (*Carry trade in developing and developed countries: A Granger causality analysis with the Toda-Yamamoto approach*) explores the carry trade in developed and developing countries during different U.S. monetary policy periods. The main contributions are related to the analysis of the long-term Granger causality between the carry trade and financial variables. This empirical analysis is possible with the procedure developed by @toda1995. There is evidence for the UIP failure (carry trade Granger causing exchange rates) for several currencies, evidencing the existence of the carry trade activity. In addition, significant differences between developed and developing countries are found for different U.S. monetary policy periods. Notably, a common result is the evidence of possible market instability and systemic risk spillovers from the carry trade activity. 

Chapter \@ref(four) (*Carry trade and negative interest rate policy in Switzerland: Low-lying fog or storm?*) uses a novel approach to examine the Swiss franc carry trade during the negative interest rate policy period in Switzerland. Following @fong2013, we construct a data set with the Swiss franc carry trade with four target currencies (U.S. dollar, euro, Japanese yen, and British pound). The focus is on a well-known institutional investor engaged in speculative investments: hedge funds. With the disentanglement of the funding currency and safe haven effects embedded in our carry trade proxy, the Swiss franc carry trade present different results depending on the target currency involved. More importantly, the violation of the UIP is present in the USD, EUR and JPY models. Moreover, there is also evidence for the relationship between increased carry trade activity and augmented systemic risk. The results pose several challenges to the SNB, which struggles to contain Swiss franc speculative activity.

In closing, Chapter \@ref(five) (*The political economy of carry trade: The real economy got carried away in Switzerland and Brazil*) innovates by estimating a Bayesian global vector autoregressive model (BGVAR) to analyze the carry trade effects in Switzerland and Brazil. Different from the previous chapters, it is a holistic study. By controlling global factors, the carry trade effects on the real economy are analyzed. Results support the tested hypothesis that there are negative carry trade effects on the Swiss and Brazilian economies. Although variant to the model specification and frequency, the results are new additions to the empirical literature on the carry trade. Furthermore, there are two main conclusions. In the Swiss case, there is a crowding out effect, where carry trade displaces real economy activity. For Brazil, the results reinforce the subordinated position of the Brazilian currency in the actual international monetary system. Indeed, the political economy approach indicates that these differences are also explained by the power relations connected to the carry trade activity. In our finance-dominated capitalism, global governance (e.g. IMF), central banks and financial investors balance their power to find common ground. Nonetheless, the “sabotage in the financial system” [@nesvetailova2020] seems to be stronger than ever.

Solutions for the carry trade puzzle are far from simple. In order to tame the negative effects of carry trade, central banks need to go further into the understanding of the anomaly. This requires better data, in line with the work done by the CFTC. Nonetheless, in essence, a system change is needed, which involves political will. Here lies the importance of the political economy of the carry trade. Individually, central banks are not able to control this type of speculation by themselves. As stressed by @tucker2011 [\text{p.} 16], "in a world of global capital markets, it is unavoidably a shared enterprise. National authorities will fail unless we work together." Hence, monetary policy cannot be the only game in town. In the national level, other institutions, like FINMA (Swiss Financial Market Supervisory Authority) in Switzerland and CMN (National Monetary Council) in Brazil, need to collaborate more with central banks to elaborate macroprudential policies more powerful to circumvent the pervasive carry trade. Another example on the right direction to combat the “sabotage in the financial system” [@nesvetailova2020] is given by the end of closed-door policymaker briefings with banks by the Bank of England [@bruce2021]. In the global level, an example in the right direction is given by the IMF by accepting more broadly capital controls. This is the kind of support from global governance that our society needs.

Carry trade is related to financial instability, as shown by the unwind of these positions during turbulent times. @tucker2011 [\text{p.} 4] says "financial stability prevails where the financial system is sufficiently resilient that worries about bad states of the world do not affect confidence in the ability of the system to deliver its core services to the rest of the economy." Since monetary policy alone cannot deal with all types of "bad states", macroprudential policies are needed to "deploy 'cyclical' instruments" [@tucker2011, \text{p.} 5]. As explained by @galati2013, \text{p.} 864, "macroprudential policy aims at preventing the macroeconomic costs of systemic financial distress, taking into account feedback effects that the behaviour of individual financial institutions have on each other, and on the whole economy." Moreover, "[t]he recent financial crisis has highlighted the need to go beyond a purely micro-based approach to financial regulation and supervision, and there is a growing consensus among policymakers that a macroprudential approach to regulation and supervision should be adopted." [@galati2013, \text{p.} 864] In Brazil, 

 >"The BCB and CMN [National Monetary Council] are jointly responsible for the management of macroprudential instruments including, among others: countercyclical capital buffers; sectoral and countercyclical capital requirements; margins and haircuts; loan-to-value ( LTV) ratios; debt-to-income ratios; limits on currency mismatches; limits on short spot FX positions; and reserve requirement ratios." [@moura2017, \text{p.} 78]

Taking the Brazilian case as an example,

 >The GFC’s first impact was detected in the FX market. Carry trade transactions were interrupted and the Brazilian real depreciated swiftly despite the high interest rate differentials relative to the main funding currencies. The higher volatility of the exchange rate led many participants to face increased margin calls, worsening their liquidity positions. Some liquidity indicators showed that smaller banks specialising in export financing were suddenly facing shortfalls in foreign currency liquidity. Offshore funding became more expensive. As confidence deteriorated, the BCB also focused on withdrawals made by institutional investors in those banks. [@moura2017, \text{p.} 82]

Consequently, the macroprudential policy tool of capital flow management was implemented in Brazil to "[s]tem volatile carry trades, lengthen maturities of the inflows, and ease persistent appreciation pressures on the currency." [@moura2017, \text{p.} 43] Regarding effectiveness, it was "moderately effective" [@moura2017, \text{p.} 43] More importantly, as shown by @uzakdogan2020 [\text{p.} 600], there is "evidence that both monetary and macroprudential policy instruments contribute to the stability of financial markets" in emerging market economies. Nevertheless, "[m]acroprudential policy instruments aiming to control capital flow volatility eventually, focus on foreign investors to prevent sudden stops. However, this study showed that it is domestic investors, rather than foreign, that respond to macroprudential policy changes." Therefore, foreign investors need to be controlled in a global level, which emphasizes the importante of the political economy approach developed in this thesis.

Indeed, the central banks of Switzerland and Brazil are in very different positions in the international monetary system. This difference in power in the international monetary system restricts the policy options for Brazil. According to @aguirre2019 [\text{p.} 104], opportunities of carry trade in developing countries 

 >"are intensified when macroprudential policies limit the ability of domestic financial institutions to provide credit to firms. Large, non-financial firms see an opportunity to obtain profits by exploiting interest rate differentials and bring in external funds that they use to lend to local firms that do not have access to international capital markets. Two elements support our hypothesis: domestic credit is negatively influenced by macroprudential policies in developing economies (but not in developed ones) and the degree of financial development of the country reinforces the positive effect of such policies on capital inflows."

Although in a simplified model, @agenor2021 [\text{p.} 1] show that the "joint use of macroprudential regulation and capital controls is also shown to provide a potent combination to manage capital inflows" in middle-income countries. Moreover, "monetary policy, macroprudential regulation, sterilization, and capital controls [...] have been used repeatedly in middle-income countries in recent years to promote macroeconomic and financial stability." [@agenor2021, \text{p.} 58] As a middle-income country, Brazil have struggled to curb the instability of capital flows. Reserve accumulation and foreign exchange market intervention have been the most used policies by the Brazilian Central Bank (BCB). The former inserts Brazil in a vicious cycle, as developed by @darista2018. In the same direction, in my opinion, this policy is related to the Brazilian "subordinated financial integration and financialisation" [@kaltenbrunner2018a]. Futhermore, regarding the latter, the BCB have profited from intervening with FX swaps in the derivative market [@sandri2020]. Nonetheless, "[t]here is a long-running debate, far from settled, on how effective FX interventions are in influencing the exchange rate or its volatility." [@patel2019, \text{p.} 32] More centrally, in middle-income countries, 

 >"the decision to intervene appears to have been increasingly driven by the goal of mitigating exchange rate volatility, rather than concerns about competitiveness, a high degree of exchange rate pass-through, currency and maturity mismatches, or the need to build foreign reserves for precautionary reasons." [@agenor2021, \text{p.} 2]

For Switzerland, the Swiss franc is demanded despite the state of the world economy. The SNB manages a currency that is a safe haven currency during crises and a funding currency in carry trade activities during expansion periods. Meanwhile, carry trade seems to help SNB's objectives to the exchange rate policy. As demonstrated in Chapter \@ref(five), an increased carry trade activity with the Swiss franc as a funding currency depreciates the Swiss franc relative to the U.S. dollar. Regarding the SNB's foreign exchange intervention, there seems to be a significant difference with Brazil. While the BCB tries to avoid excessive volatility, the SNB searches to increase the competitiveness of Swiss firms. Overall, in the context of the carry trade activity, both central banks struggle to contain the carry trade unwinding due to borrowing constraints.

While central banks cannot individually deal with the carry trade, these institutions themselves need rethinking. Globally, the question of the extension of the mandate of central banks arises to face new challenges and risks (e.g., environmental, social inequalities). New missions require new skills, and maybe new types of personnel. On the one hand, at the micro-level, it is necessary to rethink the internal organization of central banks, involving rethinking the diversity of internal staff at central banks. One example is diversity in terms of gender. @vallet2020 [\text{p.} 152] emphasizes "that an increase in gender diversity -- understood here as an increase in the feminization rate (proportion of women) in central banks, but also as a socio-demographic variable taken into account in central banks's decision-marking -- will bring about a new 'vision' and a new paradigm in the world of central banking." To the author, at stake is not only diversity per se, but how to use diversity as a crucial means to transform central banks' inner organizations radically, and more broadly, central banks as institutions. On the other hand, at the macro-level, the climate crisis will likely foster financial market instability soon, leading to more episodes of sudden stops. In this sense, "[t]he Wall Street Consensus is an elaborate effort to reorganize development interventions around partnerships with global finance", giving that "[t]he new 'development as de-risking' paradigm narrows the scope for a green developmental state that could design a just transition to low-carbon economies." [@gabor2021, \text{p.} 429]

In my opinion, democracy and the common good must overcome the existing conflict of interests in central bank management to tame the pervasive effects of the carry trade. Overall, the social responsibility of central banks is underestimated, but new research highlights the importance of this role [e.g., @vallet2021]. While analyzing the results of the macroprudential policies in Switzerland, @danthine2016 states that "[t]here is always the danger that the necessary political will may not overcome the pressures of the banking and real estate lobbies." In this sense, I think that important lobbies in global finance constantly try to block policies willing to control carry trade activities. This type of manipulation has a critical social cost.

To contribute further to building both a new vision and paradigm, future research on the topic needs to explore the carry trade impact on the functional distribution of income. It would also be interesting to test the carry trade effects in the context of the different trade structures of each country, given that Switzerland focuses on the export of complex goods while Brazil is a leading raw goods exporter. In addition, along with other econometric techniques (e.g., SVAR with data-driven identification), qualitative research using questionnaires would be welcome to increase our understanding of the carry trade activity. We could design better policies for taming the pervasive carry trade effects by interviewing market participants, central bankers, and policymakers at global governance institutions. In the context of an imminent climate crisis, which will foster market instability, more research on the carry trade activity is needed to design better policies to tame its negative spillovers on the real economy. 